-- MySQL Script generated by MySQL Workbench
-- Sat Mar  7 00:04:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demoprojectsapo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demoprojectsapo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demoprojectsapo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `demoprojectsapo` ;

-- -----------------------------------------------------
-- Table `demoprojectsapo`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoprojectsapo`.`category` (
  `id` BIGINT(20) NOT NULL,
  `categoryname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demoprojectsapo`.`category_list_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoprojectsapo`.`category_list_product` (
  `category_id` BIGINT(20) NOT NULL,
  `list_product_id` BIGINT(20) NOT NULL,
  UNIQUE INDEX `UK_d099d73mlmvg6dxs8fjd0rnc7` (`list_product_id` ASC) VISIBLE,
  INDEX `FK41uek487mk6hcfya11lgf4tt2` (`category_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demoprojectsapo`.`details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoprojectsapo`.`details` (
  `id` BIGINT(20) NOT NULL,
  `category_name` VARCHAR(255) NULL DEFAULT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `product_name` VARCHAR(255) NULL DEFAULT NULL,
  `variant_detail_name` VARCHAR(255) NULL DEFAULT NULL,
  `variant_name` VARCHAR(255) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `image` TINYBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demoprojectsapo`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoprojectsapo`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demoprojectsapo`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoprojectsapo`.`product` (
  `id` BIGINT(20) NOT NULL,
  `createdate` DATETIME NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `modifieddate` DATETIME NULL DEFAULT NULL,
  `product_name` VARCHAR(255) NULL DEFAULT NULL,
  `status` BIT(1) NOT NULL,
  `category_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK7l29ekt1x29jup80y2iigimyy` (`category_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demoprojectsapo`.`variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoprojectsapo`.`variant` (
  `id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  `variantname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKs6rahw3dxw77v1a4ovlkowf5f` (`product_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demoprojectsapo`.`variantdetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demoprojectsapo`.`variantdetail` (
  `id` BIGINT(20) NOT NULL,
  `variant_id` BIGINT(20) NULL DEFAULT NULL,
  `variantdetailname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK48qse5pthg4fr7w9ilmr8qjm3` (`variant_id` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `demoprojectsapo` ;

-- -----------------------------------------------------
-- procedure getAllProduct
-- -----------------------------------------------------

DELIMITER $$
USE `demoprojectsapo`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getAllProduct`()
BEGIN
	select product.id, product.product_name,category.categoryname,variant.variantname, variantdetail.variantdetailname,product.image ,product.createdate,product.modifieddate   from product, variant, category, variantdetail where product.id = variant.product_id and category.id = product.category_id and variantdetail.variant_id = variant.id and product.status = true;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure getProductById
-- -----------------------------------------------------

DELIMITER $$
USE `demoprojectsapo`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `getProductById`(id int)
BEGIN
	select product.id, product.product_name,category.categoryname,variant.variantname, variantdetail.variantdetailname, product.image,product.createdate,product.modifieddate   from product, variant, category, variantdetail  where product.id = id and product.id = variant.product_id and category.id = product.category_id and variantdetail.variant_id = variant.id and product.status = true;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
